name: Test var context
description: Test var context

inputs:
  environment:
    required: true
    description: The environment this native app is being deployed to
  test:
    required: false
    default: "TEST_LATEST_VAR"
    description: The environment this native app is being deployed to

outputs:
  test-var:
    value: ${{ steps.fetch-account-creds.outputs.snowsql_provider_account }}
runs:
  using: 'composite'
  steps:
    - id: fetch-account-creds
      shell: bash
      run: |
        echo "secret is ${{ secrets.TEST_SECRET }}"
        env_map='{
          "TEST_LATEST_VAR": "dummy val",
          "TEST_STAGING_VAR": "staging dummy"
        }'
        export env_map
        PROVIDER_ACCOUNT="${{ fromJSON(inputs.environment)[format('{0}', fromJSON(env.env_map)[inputs.test])]}}"

        echo "var is $PROVIDER_ACCOUNT"