name: "Test secrets"

on:
    workflow_dispatch:
    workflow_call:
        secrets:
            test_workflow:
                required: true
                description: "The workflow to test"

jobs:

    TestApproval1:
        name: Test approval 1
        runs-on: ubuntu-latest
        steps:
        - run: |
            secret=$(${{ secrets.test_workflow }} | ${{ secrets.TEST_SECRET }})
            if [ "$secret" == "${{ secrets.TEST_SECRET }}" ]; then
                echo "Secret is correct"
            else
                echo "Secret is incorrect"
            fi
          shell: bash