name: "Test secrets"

on:
    workflow_dispatch:
        inputs:
            override:
                description: "Override the default value"
                required: false
                type: string
                default: "spcs-int"
            map:
                description: "Map of environments"
                required: false
                type: string
                default: '{
                    "spcs-int": "VAR",
                    "spcs-staging": "STAGING",
                    "spcs-prod-uswest": "PROD_WESTUS_1",
                    "spcs-prod-useast": "PROD_EASTUS_1"}'
    workflow_call:
        inputs:
            override:
                description: "Override the default value"
                required: false
                type: string
                default: "spcs-int"
        # secrets:
        #     test_workflow:
        #         required: true
        #         description: "The workflow to test"
        #     another_secret:
        #         required: true
        #         description: "Another secret"

jobs:

    TestApproval1:
        name: Test approval 1
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        # - uses: ./.github/actions/test-vars
        #   id: test-vars
        #   with:
        #     environment: ${{ toJson(vars) }}
        - name: Set src account credentials
          id: set-src-account-credentials
          run: |
            map='{
                "spcs-int": "VAR",
                "spcs-staging": "STAGING",
                "spcs-prod-uswest": "PROD_WESTUS_1",
                "spcs-prod-useast": "PROD_EASTUS_1"}'
            echo "map=$map" >> $GITHUB_OUTPUT
        - run: |
            echo "override is : ${{ inputs.override }}"
            echo "valS is ${{ fromJSON(inputs.map)['spcs-int'] }}"
            echo "account is: ${{ vars[format('TEST_LATEST_%s', fromJSON(steps.set-src-account-credentials.outputs.map)[inputs.override])] }}"
          shell: bash