name: "Test secrets"

on:
    workflow_dispatch:
    workflow_call:
        inputs:
            override:
                description: "Override the default value"
                required: false
                type: string
                default: ""
        # secrets:
        #     test_workflow:
        #         required: true
        #         description: "The workflow to test"
        #     another_secret:
        #         required: true
        #         description: "Another secret"

jobs:

    TestApproval1:
        name: Test approval 1
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        # - uses: ./.github/actions/test-vars
        #   id: test-vars
        #   with:
        #     environment: ${{ toJson(vars) }}
        # - name: Set src account credentials
        #   id: set-src-account-credentials
        #   shell: bash
        #   run: |
        #     SRC_ACCOUNT="${{ vars.TEST_LATEST_VAR }}"
        #     SRC_PWD="${{ secrets.TEST_SECRET }}"
        #     if [ -n "${{ inputs.override }}" ]; then
        #         case "${{ inputs.override }}" in
        #         "latest")
        #             SRC_ACCOUNT="${{ vars.TEST_STAGING_VAR }}"
        #             SRC_PWD="${{ secrets.ANOTHER_TEST }}"
        #             ;;
        #         *)
        #             echo "option not supported"
        #             exit 1
        #             ;;
        #         esac
        #     fi
        #     echo "src_snowsql_password=$SRC_PWD" >> $GITHUB_OUTPUT
        #     echo "src_snowsql_account=$SRC_ACCOUNT" >> $GITHUB_OUTPUT
        - run: |
            echo "account is: secrets['TEST_SECRET']"
          shell: bash