name: "Test parallel approvals"

on:
    push:
    # workflow_dispatch:

jobs:

  CreateDeployment:
    name: Create deployment
    runs-on: ubuntu-latest
    outputs:
        deployment_id: ${{ steps.create-deployment.outputs.deployment_id }}
    steps:
      - name: deploy
        id: create-deployment
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: latest
          repo: Test-workflows-public
          ref: ${{ github.sha }}

  UpdateDeploymentStatus:
    name: Update deployment
    runs-on: ubuntu-latest
    needs: CreateDeployment
    steps:
      - name: Deployment Status Update
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success
          deployment-id: ${{ needs.CreateDeployment.outputs.deployment_id }}
          auto-inactive: false
