name: "Test parallel approvals"

on:
    workflow_dispatch:
    workflow_call:
        secrets:
            test_workflow:
                required: true
                description: "The workflow to test"
    # push:

jobs:

    TestApproval1:
        name: Test approval 1
        uses: ./.github/workflows/workflow_b.yaml
        secrets:
            test_workflow: ${{ secrets.test_workflow || secrets.TEST_SECRET }}
            another_secret: ${{ secrets.TEST_SECRET }}