name: "Test parallel approvals"

on:
    push:
    # workflow_dispatch:
permissions:
  id-token: write
  contents: write
  actions: write
  statuses: write
  pull-requests: write
  issues: write
  checks: write
  repository-projects: read
  packages: write
  deployments: write
jobs:

  CreateDeployment:
    name: Create deployment
    runs-on: ubuntu-latest
    outputs:
        deployment_id: ${{ steps.create-deployment.outputs.deployment_id }}
    steps:
      - name: deploy
        id: create-deployment
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: latest
          repo: Test-workflows-public
          ref: 1a574d8a7c1f2e2cf3a3056130a3a5b57911c8b2


  UpdateDeploymentStatus:
    name: Update deployment
    runs-on: ubuntu-latest
    needs: CreateDeployment
    steps:
      - name: get commit url
        id: get_commit
        run: |
          commit_url="${{ github.server_url }}/${{ github.repository }}/commit/1a574d8a7c1f2e2cf3a3056130a3a5b57911c8b2"
          echo "tag_url=${tag_url}" >> "$GITHUB_OUTPUT"
      - name: Deployment Status Update
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success
          deployment-id: ${{ needs.CreateDeployment.outputs.deployment_id }}
          log-url: ${{ steps.get_commit.outputs.tag_url }}
          auto-inactive: false
