name: "Test parallel approvals"

on:
    push:

jobs:

    # TestApproval1:
    #     name: Test approval 1
    #     runs-on: ubuntu-latest
    #     environment: require-approval
    #     steps:
    #     - run: |
    #         echo "Approval #1 test."
    #       shell: bash
    
    # TestOutput:
    #     name: Test output 1
    #     runs-on: ubuntu-latest
    #     needs: [TestApproval1]
    #     steps:
    #     - run: |
    #         echo "Sample output #1"
    #       shell: bash
    TestApproval2:
        name: Environment approval 2
        runs-on: ubuntu-latest
        environment: another-required-approval
        steps:
        - run: |
            echo "Approval #2 test."
          shell: bash
    TestOutput2:
        name: Test output 2
        runs-on: ubuntu-latest
        needs: [TestApproval2]
        steps:
        - run: |
            echo "Sample output #2"
          shell: bash