name: "Test secrets"

on:
    workflow_dispatch:
    workflow_call:
        secrets:
            test_workflow:
                required: true
                description: "The workflow to test"
            another_secret:
                required: true
                description: "Another secret"

jobs:

    TestApproval1:
        name: Test approval 1
        runs-on: ubuntu-latest
        steps:
        - run: |
            VAR_NAME="TEST_LATEST_VAR"
            SELECTED_VAR="${!VAR_NAME}"
            echo "Selected variable for environment $ENVIRONMENT is $SELECTED_VAR"
            # if [ "${{ secrets.test_workflow }}" == "${{ secrets.another_secret }}" ]; then
            #     echo "Secret is correct"
            # else
            #     echo "Secret is incorrect"
            # fi
          shell: bash